/*.$file${../::include::qm::qm_common.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: main.qm
* File:  ${../::include::qm::qm_common.h}
*
* This code has been generated by QM 5.0.1 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #   : QPC-EVAL
* Issued to   : Institution or an individual evaluating the QP/C framework
* Framework(s): qpc
* Support ends: 2020-12-31
* Product(s)  :
* This license is available only for evaluation purposes and
* the generated code is still licensed under the terms of GPL.
* Please submit request for extension of the evaluaion period at:
* <www.state-machine.com/licensing/#RequestForm>
*/
/*.$endhead${../::include::qm::qm_common.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef __QM_COMMON_H__
#define __QM_COMMON_H__

#include "qm/qm_signals.h"
#include "qm/qm_events.h"

#include "base/base.h"

#endif
