/*.$file${../::include::qm::qm_signals.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: main.qm
* File:  ${../::include::qm::qm_signals.h}
*
* This code has been generated by QM 5.0.1 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #   : QPC-EVAL
* Issued to   : Institution or an individual evaluating the QP/C framework
* Framework(s): qpc
* Support ends: 2020-12-31
* Product(s)  :
* This license is available only for evaluation purposes and
* the generated code is still licensed under the terms of GPL.
* Please submit request for extension of the evaluaion period at:
* <www.state-machine.com/licensing/#RequestForm>
*/
/*.$endhead${../::include::qm::qm_signals.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef __QM_SIGNALS_H__
#define __QM_SIGNALS_H__


#include "qpc.h"

enum qm_qpc_signals
{
    /*faba signal start value*/
    START_SIG = Q_USER_SIG,

    /*led sig*/
    LED_TIMEOUT_SIG,

    /*sys*/
    POWER_TIMEOUT_SIG,
    POWER_ON_SIG,
    POWER_START_SIG,

    /*uart*/
    UART2_RX_SIG,

    /*stream*/
    STREAM_TX_DATA_SIG,
    STREAM_RX_CMD_MSG_SIG,
    STREAM_RX_ACK_MSG_SIG,

    MAX_SIG,
};

#endif