/*.$file${../::src::qm::qm_main.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: main.qm
* File:  ${../::src::qm::qm_main.c}
*
* This code has been generated by QM 5.0.1 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #   : QPC-EVAL
* Issued to   : Institution or an individual evaluating the QP/C framework
* Framework(s): qpc
* Support ends: 2020-12-31
* Product(s)  :
* This license is available only for evaluation purposes and
* the generated code is still licensed under the terms of GPL.
* Please submit request for extension of the evaluaion period at:
* <www.state-machine.com/licensing/#RequestForm>
*/
/*.$endhead${../::src::qm::qm_main.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include <stdint.h>
#include <string.h>

#include "base/base.h"
#include "qm/qm.h"

/* Local-scope objects -----------------------------------------------------*/
Q_DEFINE_THIS_FILE

static QEvt const *l_qm_power_QSto[10];
static QEvt const *l_qm_led_QSto[10];


static QF_MPOOL_EL(QEvt)       l_small_pool[100];
static QF_MPOOL_EL(key_evt_t)  l_middle_pool[100];

static QSubscrList    l_subscrSto[MAX_SIG];
/*..........................................................................*/
int main()
{
    QF_init();

    qm_power_ctor();
    qm_led_ctor();


    /* initialize the event pools... */
    QF_poolInit(l_small_pool,   sizeof(l_small_pool),   sizeof(l_small_pool[0]));
    QF_poolInit(l_middle_pool,  sizeof(l_middle_pool),  sizeof(l_middle_pool[0]));

    /* init publish-subscribe */
    QF_psInit(l_subscrSto, Q_DIM(l_subscrSto));

    QACTIVE_START(ao_qm_power,
                  1U,
                  l_qm_power_QSto, Q_DIM(l_qm_power_QSto),
                  (void *)0, 0U,
                  (QEvt *)0);

    QACTIVE_START(ao_qm_led,
                  2U,
                  l_qm_led_QSto, Q_DIM(l_qm_led_QSto),
                  (void *)0, 0U,
                  (QEvt *)0);

    QF_run();                              /* run the QF application */

    return 0;
}


